Migrate to chartjs-test-utils
chartjs/chartjs-plugin-datalabels pull request #218
Opened 2021-02-04 11:29 UTC by kurkle

Draft, because this requires: https://github.com/chartjs/chartjs-test-utils/pull/7

2021-02-05 08:59 UTC, simonbrunel commented
Thanks @kurkle. Can you retarget this PR against `master`, then I will rebase the `chartjs-next`?

2021-02-05 09:03 UTC, kurkle commented
> Thanks @kurkle. Can you retarget this PR against `master`, then I will rebase the `chartjs-next`?

ok

2021-02-06 15:06 UTC, simonbrunel requested changes

2021-02-06 15:06 UTC, simonbrunel commented on package.json
> +    "chartjs-test-utils": "^0.1.3",
We can probably use 0.2.0 in this PR so `chartjs-next` will benefit from the async trigger mouse event.

2021-02-06 15:49 UTC, simonbrunel approved these changes

2021-02-06 15:50 UTC, merged